onload = function(){
    //Select Display Input
    var other = document.getElementById("TypeSelect");
    other.onclick = otherInput;
    //Select Display Input End

    //date
    autoGenerateDate();
    //date end

    // Clear Button
     document.getElementById("clearButton").onclick = clearForm;
    // Clear Button End
    
}
function otherInput(){  //Input Display
    var other = document.getElementById("TypeSelect").value;
    if(other == "Other"){
        document.getElementById("typeInput").style.display="block";
    }
    else{
        document.getElementById("typeInput").style.display="none";
    }
}
function autoGenerateDate(){ //date
    var date = document.getElementById("dateInput");
    var d = new Date();
    var m = d.getMonth() + 1;
    date.value =d.getDate()+"/"+m+"/"+d.getFullYear();
}

function clearForm(){
    document.getElementById("TypeSelect").selectedIndex=0;
    document.getElementById("typeInput").style.display="none";
    autoGenerateDate();
    document.getElementById("AmountInput").value ="";
}